spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 123123Aa
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  config:
    import: "optional:configserver:"
