server:
  port: 8081

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: 123123Aa
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  config:
    import: configserver:http://localhost:9296
    
eureka:
 instance:
  hostname: localhost
 client:
  registerWithEureka: true
  fetchRegistry: true
  service-url:
   efaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
 